<a href="https://colab.research.google.com/github/Kasurirohith/B23_10I2/blob/main/10I2-B23-LAB2" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
marks = np.array([
    [78, 85, 90],
    [60, 72, 68],
    [92, 88, 95],
    [45, 55, 50],
    [89, 94, 91]
])

print("Student Marks (Rows = Students, Columns = Subjects):\n", marks)


Student Marks (Rows = Students, Columns = Subjects):
 [[78 85 90]
 [60 72 68]
 [92 88 95]
 [45 55 50]
 [89 94 91]]


In [4]:
print("\nAverage marks of each student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("\nMinimum marks of each student:", np.min(marks, axis=1))
print("Maximum marks of each student:", np.max(marks, axis=1))
print("\nMinimum marks per subject:", np.min(marks, axis=0))
print("Maximum marks per subject:", np.max(marks, axis=0))



Average marks of each student: [84.33333333 66.66666667 91.66666667 50.         91.33333333]
Average marks per subject: [72.8 78.8 78.8]

Minimum marks of each student: [78 60 88 45 89]
Maximum marks of each student: [90 72 95 55 94]

Minimum marks per subject: [45 55 50]
Maximum marks per subject: [92 94 95]


In [5]:
print("\n Marks of Student 1:", marks[0])
print(" Marks of Student 3:", marks[2])
print(" Marks of Student 5:", marks[4])



 Marks of Student 1: [78 85 90]
 Marks of Student 3: [92 88 95]
 Marks of Student 5: [89 94 91]


In [6]:
print("\nBoolean Mask for marks > 80:\n", marks > 80)
students_above_80 = marks[np.any(marks > 80, axis=1)]

print("\n Students who scored above 80 in any subject:\n", students_above_80)



Boolean Mask for marks > 80:
 [[False  True  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]

 Students who scored above 80 in any subject:
 [[78 85 90]
 [92 88 95]
 [89 94 91]]


In [7]:
reshaped = marks.T
print("\n Reshaped Array (Subjects as Rows, Students as Columns):\n", reshaped)

print("\n Subject-wise Average Marks:", np.mean(reshaped, axis=1))
print(" Subject-wise Minimum Marks:", np.min(reshaped, axis=1))
print(" Subject-wise Maximum Marks:", np.max(reshaped, axis=1))



 Reshaped Array (Subjects as Rows, Students as Columns):
 [[78 60 92 45 89]
 [85 72 88 55 94]
 [90 68 95 50 91]]

 Subject-wise Average Marks: [72.8 78.8 78.8]
 Subject-wise Minimum Marks: [45 55 50]
 Subject-wise Maximum Marks: [92 94 95]


In [9]:
print(""" Analysis:
-----------------------------
- Student 3 and Student 5 have excellent marks in all subjects.
- Student 4 has consistently low marks and needs improvement.
- Subject 3 has the highest overall performance among students.
- Boolean indexing helped identify top-performing students.
- Reshaping the array makes it easy to evaluate subject-wise statistics.
""")


 Analysis:
-----------------------------
- Student 3 and Student 5 have excellent marks in all subjects.
- Student 4 has consistently low marks and needs improvement.
- Subject 3 has the highest overall performance among students.
- Boolean indexing helped identify top-performing students.
- Reshaping the array makes it easy to evaluate subject-wise statistics.

